---
spring:
    thymeleaf:
        cache: false
    datasource:
        url: jdbc:postgresql://172.17.8.101/playdb
        username: play
        password: ""
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: true
